version: '3'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./public:/var/www/public
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ../db:/var/lib/mysql:cached
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
